'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const C=require('./core.js');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'styles.css'),'utf8');
const app=fs.readFileSync(path.join(__dirname,'app.js'),'utf8');
const patches=fs.readFileSync(path.join(__dirname,'patches.js'),'utf8');
const workflow=fs.readFileSync(path.join(__dirname,'.github','workflows','test.yml'),'utf8');
assert.match(html,/data-view="decisions"/,'La navigation doit proposer l’historique des décisions.');
assert.match(html,/<details[^>]*id="captureDetails"/,'La capture doit masquer les détails au premier passage.');
assert.match(html,/id="todayWorklist"/,'Aujourd’hui doit concentrer les priorités dans une liste de travail.');
assert.match(html,/id="moreNav"/,'La navigation étroite doit proposer un accès compact aux sections secondaires.');
assert.doesNotMatch(html,/>01</,'La navigation ne doit pas utiliser de numérotation décorative.');
assert.match(html,/src="patches\.js"/,'Les correctifs fonctionnels doivent être chargés après l’application.');
assert.match(css,/--game-accent:/,'Le thème doit exposer un accent gaming sémantique.');
assert.match(css,/"Bahnschrift"/,'La typographie doit privilégier une police compacte adaptée aux interfaces gaming.');
assert.match(html,/id="captureErrorSummary"/,'La capture doit offrir un résumé des erreurs.');
assert.match(html,/class="skip-link"/,'La page doit permettre d’atteindre directement le contenu principal au clavier.');
assert.match(app,/function guardCaptureExit/,'La capture doit protéger un brouillon avant de quitter la vue.');
assert.match(app,/function projectDrillSchedule/,'Les échéances affichées des drills doivent refléter le moteur de planification.');
assert.match(app,/data-review-form/,'Une review doit permettre de compléter directement son analyse.');
assert.match(patches,/core\.addAudit\s*=/,'L’import et la maintenance doivent disposer du journal d’audit.');
assert.match(patches,/data-delete-match/,'La suppression doit être accessible depuis l’historique.');
assert.match(patches,/editIntent/,'La modification doit synchroniser review et drill.');
assert.match(patches,/function localToday/,'Les dates doivent suivre le fuseau local du navigateur.');
assert.match(workflow,/run:\s*node test-core\.js/,'La CI doit exécuter uniquement les tests Node.');
assert.doesNotMatch(workflow,/playwright|npm\s+(ci|install)/i,'La CI légère ne doit installer ni Playwright ni dépendances npm.');
let s=C.emptyState();
assert.equal(C.validateState(s).length,0);
const p=s.players[0];
const {match,decision}=C.addMatchWithDecision(s,{date:'2026-07-20',patch:'18.1',placement:4,url:'u1'},{stage:'4-1',category:'Tempo',playerId:p.id,confidence:3,cost:4,context:'test',alternatives:'A/B',action:'roll',prediction:'stabiliser',outcome:'ok',principle:'roll si faible'},{needsReview:true,makeDrill:true});
assert.equal(s.matches.length,1);assert.equal(s.decisions.length,1);assert.equal(s.reviews.length,1);assert.equal(s.drills.length,1);
assert.equal(C.audit(s).orphanDecisions,0);assert(C.learningValue(s,decision)>0);
const existing=C.ensureDrillForDecision(s,decision.id);assert.equal(existing.created,false);assert.equal(s.drills.length,1);
C.scheduleDrill(s.drills[0],4,'ma réponse');assert.equal(s.drills[0].attempts.length,1);assert(s.drills[0].due>'2026-07-20');
C.updateMatchDecision(s,match.id,{placement:3},{principle:'nouveau'});assert.equal(s.matches[0].placement,3);assert.equal(s.decisions[0].principle,'nouveau');
const exported=JSON.parse(JSON.stringify(s));const merged=C.mergeImported(C.emptyState(),exported);assert(merged.matches.some(x=>x.id===match.id));
C.deleteMatchCascade(s,match.id);assert.equal(s.matches.length,0);assert.equal(s.decisions.length,0);assert.equal(s.reviews.length,0);assert.equal(s.drills.length,0);
console.log('OK — core tests passed');
