name: Core tests

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run core tests
        run: node test-core.js
